update tests

diff --git a/modules/fixtures/postgres-client.yml b/modules/fixtures/postgres-client.yml
--- a/modules/fixtures/postgres-client.yml
+++ b/modules/fixtures/postgres-client.yml
@@ -1,4 +1,5 @@
 ---
+# this manifest contains a version with the IRSA connection check
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -9,6 +10,7 @@ spec:
     backoffLimit: 0
     template:
         spec:
+            serviceAccountName: aurora-access-sa
             restartPolicy: Never
             containers:
                 - name: postgres-client
@@ -18,19 +20,46 @@ spec:
                       - -c
                       - |
                         /bin/bash <<'EOF'
-                        set -o pipefail && \
-                        apt-get update && \
-                        apt-get install -y python3 python3-pip build-essential postgresql-client && \
-                        echo "Creating IRSA db user" && \
-                        mkdir -p /tmp/scripts  && \
-                        cp /scripts/create_aurora_pg_db.sh /tmp/scripts/create_aurora_pg_db.sh && \
-                        chmod +x /tmp/scripts/create_aurora_pg_db.sh && /tmp/scripts/create_aurora_pg_db.sh
+                        set -o pipefail
+
+                        echo "Installing dependencies..."
+                        apt-get update
+                        apt-get install -y curl postgresql-client unzip
+
+                        echo "Installing AWS CLI..."
+                        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+                        unzip awscliv2.zip
+                        ./aws/install
+
+                        echo "Creating IRSA db user using admin user"
+                        psql -h $AURORA_ENDPOINT -p $AURORA_PORT "sslmode=require dbname=$AURORA_DB_NAME user=$AURORA_USERNAME password=$AURORA_PASSWORD" \
+                          -c "CREATE USER \"${AURORA_USERNAME_IRSA}\" WITH LOGIN;" \
+                          -c "GRANT rds_iam TO \"${AURORA_USERNAME_IRSA}\";" \
+                          -c "GRANT rds_superuser TO \"${AURORA_USERNAME_IRSA}\";" \
+                          -c "GRANT ALL PRIVILEGES ON DATABASE \"${AURORA_DB_NAME}\" TO \"${AURORA_USERNAME_IRSA}\";" \
+                          -c "SELECT aurora_version();" \
+                          -c "SELECT version();" -c "\du"
+
+                        # Attempt unauthenticated access to the Aurora PostgreSQL database, expecting a failure
+                        if psql -h "$AURORA_ENDPOINT" \
+                                -p "$AURORA_PORT" \
+                                "sslmode=require dbname=$AURORA_DB_NAME user=$AURORA_USERNAME_IRSA" \
+                                -c 'SELECT version();' 2>&1 | grep -q 'password authentication failed'; then
+                          echo "Unauthenticated access failed as expected."
+                        else
+                          echo "Unauthenticated access did not fail as expected, check the configuration."
+                          exit 1
+                        fi
+
+                        echo "Testing connection using IRSA"
+                        export AWS_PG_PASSWORD=$(aws rds generate-db-auth-token --hostname $AURORA_ENDPOINT --port $AURORA_PORT \
+                            --region $AWS_REGION --username $AURORA_USERNAME_IRSA)
+                        psql -h $AURORA_ENDPOINT -p $AURORA_PORT "sslmode=require dbname=$AURORA_DB_NAME user=$AURORA_USERNAME_IRSA password=$AWS_PG_PASSWORD" \
+                          -c 'SELECT version();'
+
+                        sleep 30000
 
                         EOF
-                  volumeMounts:
-                      - name: scripts
-                        mountPath: /scripts
-                        readOnly: true
                   env:
                       - name: AURORA_ENDPOINT
                         valueFrom:
@@ -67,7 +96,3 @@ spec:
                             configMapKeyRef:
                                 name: aurora-config
                                 key: aurora_db_name
-            volumes:
-                - name: scripts
-                  configMap:
-                      name: postgres-scripts
